### ISSUE TITLE
Target temperature for Bed and Nozzle comes as '0' from Marlin

### ISSUE THREAD

**Issue by madhuni** [vivekanand1101/AstroBox#47]
When the printer initialized, the **actual temperature** for bed/nozzle comes as Room Temperature and the **target temperature** for bed/nozzle comes as '**0**'. 
We have to figure it out if the '**target**' temperature for bed/nozzle can come as Room Temperature and not '0'.

**Comment by vivekanand1101** [comment]
fixed by @madhuni
