### ISSUE TITLE
Open a on screen numeric keypad to enter the temperature for preheating process

### ISSUE THREAD

**Issue by madhuni** [vivekanand1101/AstroBox#57]
We can have a model containing the numeric keypad open whenever temperature value is needed to be added in preheating process.
for ex:
http://a.kabachnik.info/numeric-keypad-for-jquerymobile.html
http://a.kabachnik.info/jquery-numpad.html

**Comment by madhuni** [comment]
Finally, our brand new custom Number Pad is added in the software. 👍  👍

**Comment by vivekanand1101** [comment]
fixed in #103
